// Auto-generated by migration script
export type Destination = {
  id: string;
  city: string;
  district: string;
  tier: number;
  imagePath: string;
  description: string;
};

export const destinations: Destination[] = [
  {
    "id": "1",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_272bccd301.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "2",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_9ce1eac017.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "3",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_9ef6619ab5.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "4",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_fc7719d82d.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "5",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Jagalchi_market_waterfront_busan_23354e6dcb.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "6",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Jagalchi_market_waterfront_busan_dfe915bd48.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "7",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Road_leading_to_ocean_tram_852c2545ac.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "8",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Temple_on_coastal_cliff_4aa446cd43.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "9",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Temple_on_coastal_cliff_73da5c1f62.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "10",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Woman_looking_at_ocean_train_8d40fa1a14.jpeg",
    "description": "Beautiful Busan view."
  },
  {
    "id": "11",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_dramatic_atmospheric_travel_photograph_taken_fro_a0cf42a564.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "12",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_premium_editorial_lifestyle_photograph_taken_fro_39f32dd8c5.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "13",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Crowded_pub_with_ocean_view_4b3ff2e95b.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "14",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Crowded_pub_with_ocean_view_79ad7298d4.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "15",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Diamond_bridge_glowing_night_24029fba63.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "16",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Diamond_bridge_glowing_night_a9a24383dd.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "17",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Drone_light_show_over_beach_0f2733c9f2.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "18",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Drone_light_show_over_beach_8dca025a73.jpeg",
    "description": "Beautiful 광안리 view."
  },
  {
    "id": "19",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_dynamic_highend_editorial_photograph_of_the_mass_782b73434e.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "20",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Couple_pointing_at_vintage_shop_16883c9d7f.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "21",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Downtown_streets_busan_night_ac142b9dab.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "22",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Downtown_streets_busan_night_e16a02f178.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "23",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Seomyeon_pojangmacha_alley_at_night_02e63571d7.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "24",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Seomyeon_pojangmacha_alley_at_night_04280faef2.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "25",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Youth_drinking_espresso_outdoors_8eaf78d9e3.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "26",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Youth_drinking_espresso_outdoors_ae5300fd67.jpeg",
    "description": "Beautiful 서면 view."
  },
  {
    "id": "27",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_cinematic_travel_photograph_of_haeu_e9b5575ea7.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "28",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Haeundae_street_at_night_cd00636630.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "29",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Haeundae_street_at_night_fe3b07d6d5.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "30",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Marine_city_skyline_at_night_a3203bfaed.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "31",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_People_relaxing_on_sunbeds_1d13d26ff9.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "32",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_People_relaxing_on_sunbeds_b4fe3bd324.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "33",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Trendy_cafe_alleyway_behind_beach_95a16b6f29.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "34",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Trendy_cafe_alleyway_behind_beach_c194c1e0f6.jpeg",
    "description": "Beautiful 해운대 view."
  },
  {
    "id": "35",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Couple_relaxing_by_suv_2ab42242bc.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "36",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Couple_relaxing_by_suv_ffa61357e3.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "37",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Couple_relaxing_in_hot_spring_81659523d7.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "38",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Man_relaxing_in_hot_spring_ffae1e8531.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "39",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Stars_over_river_and_campfire_283aebbc3a.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "40",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Stars_over_river_and_campfire_ad100db507.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "41",
    "city": "Chungju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Chungju_Traveler_at_lake_fortress_wall_6374ceab8e.jpeg",
    "description": "Beautiful Chungju view."
  },
  {
    "id": "42",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_A_dynamic_vibrant_professional_landscape_photograp_ac745a964e.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "43",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_A_dynamic_vibrant_professional_landscape_photograp_ccba847d93.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "44",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_A_powerful_highend_editorial_landscape_photograph_cff16746c4.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "45",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Resort_complex_on_bomun_lake_6416cc3525.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "46",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Resort_complex_on_bomun_lake_c69134f4a2.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "47",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Wooden_pavilion_on_stone_pillars_0c1a8a5a09.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "48",
    "city": "Gyeongju",
    "district": "보문호수리조트",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Wooden_pavilion_on_stone_pillars_fd5ac5b2c2.jpeg",
    "description": "Beautiful 보문호수리조트 view."
  },
  {
    "id": "49",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_A_powerful_highend_editorial_landscape_photograph_bbc107ef6c.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "50",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Bulguksa_temple_stone_staircases_3e74ba1a09.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "51",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Bulguksa_temple_stone_staircases_631d186477.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "52",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Temple_roof_dancheong_paint_eaves_4a0191e04d.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "53",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Temple_roof_dancheong_paint_eaves_bef285e6c0.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "54",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Twin_pagodas_in_temple_courtyard_52e8d774d8.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "55",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Twin_pagodas_in_temple_courtyard_549b408da2.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "56",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Wooden_corridors_of_bulguksa_temple_2abfeaf403.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "57",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Wooden_corridors_of_bulguksa_temple_80b40c4782.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "58",
    "city": "Gyeongju",
    "district": "불국사",
    "tier": 2,
    "imagePath": "/images/destinations/Gyeongju_Wooden_pavilion_overlooking_pond_0d8fb14871.jpeg",
    "description": "Beautiful 불국사 view."
  },
  {
    "id": "59",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Couple_walking_on_wooden_boardwalk_79356f6dab.jpeg",
    "description": "Beautiful Jeju view."
  },
  {
    "id": "60",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Crater_on_mount_hallasan_summit_32fc4f45a1.jpeg",
    "description": "Beautiful Jeju view."
  },
  {
    "id": "61",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_dynamic_highend_editorial_lifestyle_photograph_o_b8079a0073.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "62",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_dynamic_highend_editorial_lifestyle_photograph_o_bc41a8f283.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "63",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_professional_aweinspiring_landscape_photograph_o_5b7eaff21a.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "64",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_professional_aweinspiring_landscape_photograph_o_6fd037253b.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "65",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Bbq_restaurant_overlooking_ocean_aafa7d76a4.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "66",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Couple_walking_on_street_a19d91f341.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "67",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Couple_walking_on_street_ca1fb9ee68.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "68",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Luxury_resort_on_jeju_island_503ba2efb1.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "69",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Luxury_resort_on_jeju_island_c3970231c3.jpeg",
    "description": "Beautiful 서귀포 view."
  },
  {
    "id": "70",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_highend_editorial_travel_photograph_looking_up_a_d8c2920347.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "71",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_powerful_highend_editorial_travel_photograph_of_3620f359a9.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "72",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_powerful_highend_editorial_travel_photograph_of_9f03ffa552.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "73",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Cafe_with_view_of_volcano_c7dc8ba070.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "74",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Canola_field_before_mountain_23b6c9132d.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "75",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Canola_field_before_mountain_2ee5ad2a34.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "76",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Empty_cafe_with_coffee_55888e6e1f.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "77",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Volcanic_crater_in_turquoise_ocean_9afcac1cbe.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "78",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Volcanic_crater_in_turquoise_ocean_b7ac2c67bd.jpeg",
    "description": "Beautiful 성산일출봉 view."
  },
  {
    "id": "79",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_dynamic_highend_editorial_travel_photograph_of_a_c7e7c863bc.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "80",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Cafe_street_on_volcanic_rocks_4d18ece0d8.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "81",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Cafe_street_on_volcanic_rocks_ab9293f949.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "82",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Iced_drinks_and_desserts_cafe_77ee160e4a.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "83",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Iced_drinks_and_desserts_cafe_aa26fed301.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "84",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Shop_on_hill_with_tourists_6c2ae6e23d.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "85",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Shop_on_hill_with_tourists_ad232ad26f.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "86",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Travelers_riding_transparent_kayaks_9900c9216b.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "87",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Travelers_riding_transparent_kayaks_ea9ba0b390.jpeg",
    "description": "Beautiful 애월 view."
  },
  {
    "id": "88",
    "city": "Seoul",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_breathtaking_ultrapremium_architectural_photogra_c26949d07b.jpeg",
    "description": "Beautiful Seoul view."
  },
  {
    "id": "89",
    "city": "Seoul",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Couple_walking_in_alleyway_dc1f906cb6.jpeg",
    "description": "Beautiful Seoul view."
  },
  {
    "id": "90",
    "city": "Seoul",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Seoul_tower_piercing_sky_cd3a743c2f.jpeg",
    "description": "Beautiful Seoul view."
  },
  {
    "id": "91",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_highend_fashion_editorial_photograph_of_the_luxu_018ab926be.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "92",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_highend_fashion_editorial_photograph_of_the_luxu_ccb2ce8e2f.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "93",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_highend_fashion_editorial_photograph_of_the_luxu_cf902b6d1a.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "94",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_raw_atmospheric_travel_photograph_outside_a_tren_ec94c17158.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "95",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Gangnam_boulevard_seoul_night_2a6c4fb013.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "96",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Gangnam_boulevard_seoul_night_7a9482e488.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "97",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Professionals_working_in_cafe_09e19e8213.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "98",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Professionals_working_in_cafe_70f7d8686f.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "99",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Professionals_working_in_cafe_989ae699f5.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "100",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Starfield_library_inside_coex_mall_487ea86427.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "101",
    "city": "Seoul",
    "district": "강남",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Starfield_library_inside_coex_mall_c20d8f6f21.jpeg",
    "description": "Beautiful 강남 view."
  },
  {
    "id": "102",
    "city": "Seoul",
    "district": "경복궁",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_breathtaking_highly_atmospheric_editorial_landsc_06b2e5a711.jpeg",
    "description": "Beautiful 경복궁 view."
  },
  {
    "id": "103",
    "city": "Seoul",
    "district": "경복궁",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_A_breathtaking_highly_atmospheric_editorial_landsc_631021fa6b.jpeg",
    "description": "Beautiful 경복궁 view."
  },
  {
    "id": "104",
    "city": "Seoul",
    "district": "경복궁",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Gyeongbokgung_palace_misty_morning_04de75fdb4.jpeg",
    "description": "Beautiful 경복궁 view."
  },
  {
    "id": "105",
    "city": "Seoul",
    "district": "경복궁",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Gyeongbokgung_palace_misty_morning_c2f3ad2205.jpeg",
    "description": "Beautiful 경복궁 view."
  },
  {
    "id": "106",
    "city": "Seoul",
    "district": "명동",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Street_shoppers_myeongdong_seoul_60855f3a7d.jpeg",
    "description": "Beautiful 명동 view."
  },
  {
    "id": "107",
    "city": "Seoul",
    "district": "명동",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Street_shoppers_myeongdong_seoul_b122a85c23.jpeg",
    "description": "Beautiful 명동 view."
  },
  {
    "id": "108",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Antique_furniture_street_seoul_a7b47c4a86.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "109",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Back_alleys_itaewon_seoul_evening_7c8c4960a7.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "110",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Back_alleys_itaewon_seoul_evening_a0b9236760.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "111",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Back_alleys_itaewon_seoul_evening_d4da29de71.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "112",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Back_alleys_itaewon_seoul_evening_f8bc5bfa8f.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "113",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Cocktails_on_rooftop_bar_b38d0dbdff.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "114",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Hbc_hillside_street_seoul_73935b9e1f.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "115",
    "city": "Seoul",
    "district": "이태원",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Hbc_hillside_street_seoul_7ef45c0eaa.jpeg",
    "description": "Beautiful 이태원 view."
  },
  {
    "id": "116",
    "city": "Seoul",
    "district": "홍대",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Cafe_with_people_relaxing_fca4ea77e1.jpeg",
    "description": "Beautiful 홍대 view."
  },
  {
    "id": "117",
    "city": "Seoul",
    "district": "홍대",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Seoul_nightlife_street_evening_2dff359737.jpeg",
    "description": "Beautiful 홍대 view."
  },
  {
    "id": "118",
    "city": "Seoul",
    "district": "홍대",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Street_at_night_colorful_signs_9d7f536cb0.jpeg",
    "description": "Beautiful 홍대 view."
  },
  {
    "id": "119",
    "city": "Seoul",
    "district": "홍대",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Street_busker_performing_live_music_8addd1db52.jpeg",
    "description": "Beautiful 홍대 view."
  },
  {
    "id": "120",
    "city": "Seoul",
    "district": "홍대",
    "tier": 1,
    "imagePath": "/images/destinations/Seoul_Youths_walking_past_graffiti_murals_938f766861.jpeg",
    "description": "Beautiful 홍대 view."
  },
  {
    "id": "121",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_A_breathtaking_professional_national_geographicsty_ddc24bc0c5.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "122",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_City_park_reflecting_mountain_b858d6d9ba.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "123",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Friends_relaxing_with_coffee_cafe_bcb924ac4f.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "124",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Hiker_dipping_hand_in_stream_3a59155cab.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "125",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Hiker_dwarfed_by_stone_pagodas_88c2c81acf.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "126",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Hiker_on_mountain_overlooking_city_1b7177f12b.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "127",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Hiker_on_mountain_overlooking_city_6f0c6bc08d.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "128",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Train_station_with_cherry_blossoms_918188e3e2.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "129",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Woman_admiring_water_reflection_375dd1d103.jpeg",
    "description": "Beautiful Wonju view."
  },
  {
    "id": "130",
    "city": "Wonju",
    "district": "",
    "tier": 4,
    "imagePath": "/images/destinations/Wonju_Woman_admiring_water_reflection_66e693eb77.jpeg",
    "description": "Beautiful Wonju view."
  }
,
  {
    "id": "500",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_cinematic_travel_photograph_of_haeu_e9b5575ea7.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "501",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_272bccd301.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "502",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_9ce1eac017.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "503",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_9ef6619ab5.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "504",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_breathtaking_ultravibrant_travel_magazine_cover_fc7719d82d.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "505",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_dramatic_atmospheric_travel_photograph_taken_fro_a0cf42a564.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "506",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_dynamic_highend_editorial_photograph_of_the_mass_782b73434e.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "507",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_A_premium_editorial_lifestyle_photograph_taken_fro_39f32dd8c5.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "508",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Couple_pointing_at_vintage_shop_16883c9d7f.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "509",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Crowded_pub_with_ocean_view_4b3ff2e95b.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "510",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Crowded_pub_with_ocean_view_79ad7298d4.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "511",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Diamond_bridge_glowing_night_24029fba63.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "512",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Diamond_bridge_glowing_night_a9a24383dd.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "513",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Downtown_streets_busan_night_ac142b9dab.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "514",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Downtown_streets_busan_night_e16a02f178.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "515",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Drone_light_show_over_beach_0f2733c9f2.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "516",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Drone_light_show_over_beach_8dca025a73.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "517",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Haeundae_street_at_night_cd00636630.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "518",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Haeundae_street_at_night_fe3b07d6d5.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "519",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Jagalchi_market_waterfront_busan_23354e6dcb.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "520",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Jagalchi_market_waterfront_busan_dfe915bd48.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "521",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Marine_city_skyline_at_night_a3203bfaed.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "522",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_People_relaxing_on_sunbeds_1d13d26ff9.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "523",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_People_relaxing_on_sunbeds_b4fe3bd324.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "524",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Road_leading_to_ocean_tram_852c2545ac.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "525",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Seomyeon_pojangmacha_alley_at_night_02e63571d7.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "526",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Seomyeon_pojangmacha_alley_at_night_04280faef2.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "527",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Temple_on_coastal_cliff_4aa446cd43.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "528",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Temple_on_coastal_cliff_73da5c1f62.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "529",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Trendy_cafe_alleyway_behind_beach_95a16b6f29.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "530",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Trendy_cafe_alleyway_behind_beach_c194c1e0f6.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "531",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Woman_looking_at_ocean_train_8d40fa1a14.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "532",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Youth_drinking_espresso_outdoors_8eaf78d9e3.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "533",
    "city": "Busan",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_Youth_drinking_espresso_outdoors_ae5300fd67.jpeg",
    "description": "Experience the charm of Busan."
  },
  {
    "id": "534",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_A_dramatic_atmospheric_travel_photograph_taken_fro_a0cf42a564.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "535",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_A_premium_editorial_lifestyle_photograph_taken_fro_39f32dd8c5.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "536",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_Crowded_pub_with_ocean_view_4b3ff2e95b.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "537",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_Crowded_pub_with_ocean_view_79ad7298d4.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "538",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_Diamond_bridge_glowing_night_24029fba63.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "539",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_Diamond_bridge_glowing_night_a9a24383dd.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "540",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_Drone_light_show_over_beach_0f2733c9f2.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "541",
    "city": "Busan",
    "district": "광안리",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_광안리_Drone_light_show_over_beach_8dca025a73.jpeg",
    "description": "Experience the charm of 광안리, Busan."
  },
  {
    "id": "542",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_A_dynamic_highend_editorial_photograph_of_the_mass_782b73434e.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "543",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Couple_pointing_at_vintage_shop_16883c9d7f.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "544",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Downtown_streets_busan_night_ac142b9dab.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "545",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Downtown_streets_busan_night_e16a02f178.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "546",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Seomyeon_pojangmacha_alley_at_night_02e63571d7.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "547",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Seomyeon_pojangmacha_alley_at_night_04280faef2.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "548",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Youth_drinking_espresso_outdoors_8eaf78d9e3.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "549",
    "city": "Busan",
    "district": "서면",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_서면_Youth_drinking_espresso_outdoors_ae5300fd67.jpeg",
    "description": "Experience the charm of 서면, Busan."
  },
  {
    "id": "550",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_A_breathtaking_cinematic_travel_photograph_of_haeu_e9b5575ea7.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "551",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_Haeundae_street_at_night_cd00636630.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "552",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_Haeundae_street_at_night_fe3b07d6d5.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "553",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_Marine_city_skyline_at_night_a3203bfaed.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "554",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_People_relaxing_on_sunbeds_1d13d26ff9.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "555",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_People_relaxing_on_sunbeds_b4fe3bd324.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "556",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_Trendy_cafe_alleyway_behind_beach_95a16b6f29.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "557",
    "city": "Busan",
    "district": "해운대",
    "tier": 1,
    "imagePath": "/images/destinations/Busan_해운대_Trendy_cafe_alleyway_behind_beach_c194c1e0f6.jpeg",
    "description": "Experience the charm of 해운대, Busan."
  },
  {
    "id": "558",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_dynamic_highend_editorial_lifestyle_photograph_o_b8079a0073.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "559",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_dynamic_highend_editorial_lifestyle_photograph_o_bc41a8f283.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "560",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_dynamic_highend_editorial_travel_photograph_of_a_c7e7c863bc.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "561",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_highend_editorial_travel_photograph_looking_up_a_d8c2920347.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "562",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_powerful_highend_editorial_travel_photograph_of_3620f359a9.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "563",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_powerful_highend_editorial_travel_photograph_of_9f03ffa552.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "564",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_professional_aweinspiring_landscape_photograph_o_5b7eaff21a.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "565",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_A_professional_aweinspiring_landscape_photograph_o_6fd037253b.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "566",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Bbq_restaurant_overlooking_ocean_aafa7d76a4.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "567",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Cafe_street_on_volcanic_rocks_4d18ece0d8.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "568",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Cafe_street_on_volcanic_rocks_ab9293f949.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "569",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Cafe_with_view_of_volcano_c7dc8ba070.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "570",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Canola_field_before_mountain_23b6c9132d.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "571",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Canola_field_before_mountain_2ee5ad2a34.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "572",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Couple_walking_on_street_a19d91f341.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "573",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Couple_walking_on_street_ca1fb9ee68.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "574",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Couple_walking_on_wooden_boardwalk_79356f6dab.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "575",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Crater_on_mount_hallasan_summit_32fc4f45a1.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "576",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Empty_cafe_with_coffee_55888e6e1f.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "577",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Iced_drinks_and_desserts_cafe_77ee160e4a.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "578",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Iced_drinks_and_desserts_cafe_aa26fed301.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "579",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Luxury_resort_on_jeju_island_503ba2efb1.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "580",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Luxury_resort_on_jeju_island_c3970231c3.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "581",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Shop_on_hill_with_tourists_6c2ae6e23d.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "582",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Shop_on_hill_with_tourists_ad232ad26f.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "583",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Travelers_riding_transparent_kayaks_9900c9216b.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "584",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Travelers_riding_transparent_kayaks_ea9ba0b390.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "585",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Volcanic_crater_in_turquoise_ocean_9afcac1cbe.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "586",
    "city": "Jeju",
    "district": "",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_Volcanic_crater_in_turquoise_ocean_b7ac2c67bd.jpeg",
    "description": "Experience the charm of Jeju."
  },
  {
    "id": "587",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_A_dynamic_highend_editorial_lifestyle_photograph_o_b8079a0073.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "588",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_A_dynamic_highend_editorial_lifestyle_photograph_o_bc41a8f283.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "589",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_A_professional_aweinspiring_landscape_photograph_o_5b7eaff21a.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "590",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_A_professional_aweinspiring_landscape_photograph_o_6fd037253b.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "591",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_Bbq_restaurant_overlooking_ocean_aafa7d76a4.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "592",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_Couple_walking_on_street_a19d91f341.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "593",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_Couple_walking_on_street_ca1fb9ee68.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "594",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_Luxury_resort_on_jeju_island_503ba2efb1.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "595",
    "city": "Jeju",
    "district": "서귀포",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_서귀포_Luxury_resort_on_jeju_island_c3970231c3.jpeg",
    "description": "Experience the charm of 서귀포, Jeju."
  },
  {
    "id": "596",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_A_highend_editorial_travel_photograph_looking_up_a_d8c2920347.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "597",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_A_powerful_highend_editorial_travel_photograph_of_3620f359a9.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "598",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_A_powerful_highend_editorial_travel_photograph_of_9f03ffa552.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "599",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_Cafe_with_view_of_volcano_c7dc8ba070.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "600",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_Canola_field_before_mountain_23b6c9132d.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "601",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_Canola_field_before_mountain_2ee5ad2a34.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "602",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_Empty_cafe_with_coffee_55888e6e1f.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "603",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_Volcanic_crater_in_turquoise_ocean_9afcac1cbe.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "604",
    "city": "Jeju",
    "district": "성산일출봉",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_성산일출봉_Volcanic_crater_in_turquoise_ocean_b7ac2c67bd.jpeg",
    "description": "Experience the charm of 성산일출봉, Jeju."
  },
  {
    "id": "605",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_A_dynamic_highend_editorial_travel_photograph_of_a_c7e7c863bc.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "606",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Cafe_street_on_volcanic_rocks_4d18ece0d8.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "607",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Cafe_street_on_volcanic_rocks_ab9293f949.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "608",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Iced_drinks_and_desserts_cafe_77ee160e4a.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "609",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Iced_drinks_and_desserts_cafe_aa26fed301.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "610",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Shop_on_hill_with_tourists_6c2ae6e23d.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "611",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Shop_on_hill_with_tourists_ad232ad26f.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "612",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Travelers_riding_transparent_kayaks_9900c9216b.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  },
  {
    "id": "613",
    "city": "Jeju",
    "district": "애월",
    "tier": 1,
    "imagePath": "/images/destinations/Jeju_애월_Travelers_riding_transparent_kayaks_ea9ba0b390.jpeg",
    "description": "Experience the charm of 애월, Jeju."
  }
];

export const districtToEnglish: Record<string, string> = {
  '광안리': 'Gwangalli',
  '서면': 'Seomyeon',
  '해운대': 'Haeundae',
  '보문호수리조트': 'Bomun Lake Resort',
  '불국사': 'Bulguksa Temple',
  '서귀포': 'Seogwipo',
  '성산일출봉': 'Seongsan Ilchulbong',
  '애월': 'Aewol',
  '강남': 'Gangnam',
  '경복궁': 'Gyeongbokgung Palace',
  '명동': 'Myeongdong',
  '이태원': 'Itaewon',
  '홍대': 'Hongdae',
};

export const getDestinationsByTier = (tier: number | string): (Destination & { src: string, districtEn: string })[] => {
  const numTier = typeof tier === 'string' ? parseInt(tier.replace('Tier ', ''), 10) : tier;
  
  // Filter destinations by the requested tier
  const tierDestinations = destinations.filter((d) => d.tier === numTier);
  
  // Create a map to keep only ONE image per unique location (city + district)
  const uniqueLocationsMap = new Map<string, Destination>();
  for (const dest of tierDestinations) {
    const key = `${dest.city}-${dest.district || 'main'}`;
    // Optionally, we could randomize which photo gets picked, but picking first is fine
    if (!uniqueLocationsMap.has(key)) {
      uniqueLocationsMap.set(key, dest);
    }
  }
  
  // Convert map values back to array and append src property and english district
  return Array.from(uniqueLocationsMap.values()).map((d) => ({
    ...d,
    src: d.imagePath,
    districtEn: d.district ? (districtToEnglish[d.district] || d.district) : d.city,
  }));
};
